// Data service — reads from static JSON files (generated by sync script)
// No Supabase client needed in browser — avoids secret key exposure

const DATA_BASE = '/data';

const cache: Record<string, any[]> = {};

async function loadTable(table: string): Promise<any[]> {
  if (cache[table]) return cache[table];
  const resp = await fetch(`${DATA_BASE}/${table}.json`);
  if (!resp.ok) throw new Error(`Failed to load ${table}: ${resp.status}`);
  const data = await resp.json();
  cache[table] = data;
  return data;
}

const getStartDate = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString().split('T')[0];
};

function filterByDate(data: any[], days: number) {
  const start = getStartDate(days);
  return data.filter((r: any) => r.date >= start);
}

export const fetchDailyMetrics = async (days: number) => {
  const data = await loadTable('metrika_daily_metrics');
  return filterByDate(data, days).sort((a: any, b: any) => a.date.localeCompare(b.date));
};

export const fetchFunnelData = async (days: number) => {
  const data = await loadTable('metrika_funnel_daily');
  const filtered = filterByDate(data, days);

  const aggregated = filtered.reduce((acc: any, curr: any) => {
    const step = acc.find((s: any) => s.step_name === curr.step_name);
    if (step) {
      step.unique_sessions += curr.unique_sessions;
      step.unique_users += curr.unique_users;
    } else {
      acc.push({ ...curr });
    }
    return acc;
  }, []);

  return aggregated.sort((a: any, b: any) => a.step_order - b.step_order);
};

export const fetchTrafficSources = async (days: number) => {
  const data = await loadTable('metrika_traffic_sources');
  const filtered = filterByDate(data, days);

  const aggregated = filtered.reduce((acc: any, curr: any) => {
    const key = `${curr.source} / ${curr.medium}`;
    if (!acc[key]) {
      acc[key] = {
        name: key,
        source: curr.source,
        medium: curr.medium,
        sessions: 0,
        active_users: 0,
        new_users: 0,
        conversions: 0,
        revenue: 0,
      };
    }
    acc[key].sessions += curr.sessions || 0;
    acc[key].active_users += curr.active_users || 0;
    acc[key].new_users += curr.new_users || 0;
    acc[key].conversions += curr.conversions || 0;
    acc[key].revenue += curr.revenue || 0;
    return acc;
  }, {});

  return Object.values(aggregated)
    .sort((a: any, b: any) => b.sessions - a.sessions);
};

export const fetchDeviceData = async (days: number) => {
  const data = await loadTable('metrika_devices');
  const filtered = filterByDate(data, days);

  const aggregated = filtered.reduce((acc: any, curr: any) => {
    const cat = curr.device_category;
    if (!acc[cat]) {
      acc[cat] = {
        name: cat === 'mobile' ? 'Мобильные' : cat === 'desktop' ? 'Десктоп' : cat === 'tablet' ? 'Планшеты' : cat,
        device_category: cat,
        sessions: 0,
        active_users: 0,
        conversions: 0,
        add_to_carts: curr.add_to_carts || 0,
        revenue: 0,
        bounce_rate_sum: 0,
        bounce_rate_count: 0,
        avg_session_dur_sum: 0,
      };
    }
    acc[cat].sessions += curr.sessions || 0;
    acc[cat].active_users += curr.active_users || 0;
    acc[cat].conversions += curr.conversions || 0;
    acc[cat].add_to_carts += curr.add_to_carts || 0;
    acc[cat].revenue += curr.revenue || 0;
    acc[cat].bounce_rate_sum += (curr.bounce_rate || 0) * (curr.sessions || 0);
    acc[cat].bounce_rate_count += curr.sessions || 0;
    acc[cat].avg_session_dur_sum += (curr.avg_session_duration || 0) * (curr.sessions || 0);
    return acc;
  }, {});

  return Object.values(aggregated).map((d: any) => ({
    ...d,
    bounce_rate: d.bounce_rate_count > 0 ? d.bounce_rate_sum / d.bounce_rate_count : 0,
    avg_session_duration: d.bounce_rate_count > 0 ? d.avg_session_dur_sum / d.bounce_rate_count : 0,
    conversion: d.sessions > 0 ? (d.conversions / d.sessions) * 100 : 0,
    cartRate: d.sessions > 0 ? (d.add_to_carts / d.sessions) * 100 : 0,
  }))
  .sort((a: any, b: any) => b.sessions - a.sessions);
};

export const fetchTopPages = async (days: number) => {
  const data = await loadTable('metrika_pages');
  const filtered = filterByDate(data, days);

  const aggregated = filtered.reduce((acc: any, curr: any) => {
    const path = curr.page_path;
    if (!acc[path]) {
      acc[path] = {
        page_path: path,
        page_title: curr.page_title || path,
        screen_page_views: 0,
        active_users: 0,
        bounce_rate_sum: 0,
        bounce_rate_count: 0,
        engagement_sum: 0,
      };
    }
    acc[path].screen_page_views += curr.screen_page_views || 0;
    acc[path].active_users += curr.active_users || 0;
    acc[path].bounce_rate_sum += (curr.bounce_rate || 0) * (curr.screen_page_views || 0);
    acc[path].bounce_rate_count += curr.screen_page_views || 0;
    acc[path].engagement_sum += (curr.avg_engagement_time || 0) * (curr.active_users || 0);
    return acc;
  }, {});

  return Object.values(aggregated).map((d: any) => ({
    ...d,
    bounce_rate: d.bounce_rate_count > 0 ? d.bounce_rate_sum / d.bounce_rate_count : 0,
    avg_engagement_time: d.active_users > 0 ? d.engagement_sum / d.active_users : 0,
  }))
  .sort((a: any, b: any) => b.screen_page_views - a.screen_page_views);
};

export const fetchSearchTerms = async (days: number) => {
  const data = await loadTable('metrika_search_terms');
  const filtered = filterByDate(data, days);

  const aggregated = filtered.reduce((acc: any, curr: any) => {
    const term = curr.search_term;
    if (!acc[term]) {
      acc[term] = {
        search_term: term,
        search_count: 0,
        unique_users: 0,
      };
    }
    acc[term].search_count += curr.search_count || 0;
    acc[term].unique_users += curr.unique_users || 0;
    return acc;
  }, {});

  return Object.values(aggregated)
    .sort((a: any, b: any) => b.search_count - a.search_count);
};

export const fetchSankeyData = async (days: number) => {
  const data = await loadTable('metrika_sankey');
  const filtered = filterByDate(data, days);

  // Агрегируем по парам (from → to)
  const aggregated = filtered.reduce((acc: any, curr: any) => {
    const key = `${curr.from}|||${curr.to}`;
    if (!acc[key]) {
      acc[key] = {
        from: curr.from,
        to: curr.to,
        transitions: 0,
        users: 0,
      };
    }
    acc[key].transitions += curr.transitions || 0;
    acc[key].users += curr.users || 0;
    return acc;
  }, {});

  return Object.values(aggregated)
    .sort((a: any, b: any) => b.transitions - a.transitions);
};

export const fetchEcommerceData = async (days: number) => {
  const data = await loadTable('metrika_ecommerce');
  const filtered = filterByDate(data, days);

  const aggregated = filtered.reduce((acc: any, curr: any) => {
    const event = curr.event_name;
    if (!acc[event]) {
      acc[event] = {
        event_name: event,
        event_count: 0,
        unique_users: 0,
        total_revenue: 0,
      };
    }
    acc[event].event_count += curr.event_count || 0;
    acc[event].unique_users += curr.unique_users || 0;
    acc[event].total_revenue += curr.total_revenue || 0;
    return acc;
  }, {});

  return aggregated;
};
